# Generated by Django 5.0.3 on 2024-04-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_demo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
