# Generated by Django 5.0.3 on 2024-04-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
