# Generated by Django 5.0.3 on 2024-04-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_product_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usd_price',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
