# Generated by Django 5.0.3 on 2024-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_vendor_mobile_vendor_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish_status',
            field=models.BooleanField(default=False),
        ),
    ]
