# Generated by Django 5.0.3 on 2024-04-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_product_publish_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
