# Generated by Django 5.0.3 on 2024-05-02 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_vendor_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_img',
            field=models.ImageField(null=True, upload_to='category_imgs/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product', to='main.productcategory'),
        ),
    ]
