# Generated by Django 5.0.3 on 2024-05-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_productcategory_cat_img_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trans_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
